
import type { Metadata } from "next";
import "./globals.css";
import { ColorProvider } from "./context/ColorContext";
import LenisScroll from "./providers/LenisScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <LenisScroll>
        <ColorProvider>{children}</ColorProvider>
        </LenisScroll>  
      </body>
    </html>
  );
}
